listaDeNumeros = list(map(int, input().split()))
numerosOrdenados = sorted(listaDeNumeros)
print(numerosOrdenados[0])
print(numerosOrdenados[1])
print(numerosOrdenados[2])
print()
print(listaDeNumeros[0])
print(listaDeNumeros[1])
print(listaDeNumeros[2])